### ISSUE TITLE
Incompatability with hscan and some other incompatibilities.

### ISSUE THREAD

**Issue by borg286** [KvrocksLabs/kvrocks#3]
There is a python ORM library for redis called walrus. It has a very rich set of tests. I found this helpful in identifying problems with compatability with stock redis. https://github.com/coleifer/walrus
I was able to run these tests against your redis and it found some issues

Here is the output of the test run.
https://pastebin.com/mFfEjWPT

I have verified that stock redis passes all the tests.

The tweaks I had to do to the tests was to pass in the password='foobared' to 2 places: runtests.py does a call to Redis().Info() which needs the password set, and
walrus/tests/base.py which also needs the password passed into the Redis() call.

I'd cut a bug for each issue, but I think odds are that once you get the tests running locally you'll be able to find other incompatibilities and fix them.

**Comment by git-hulk** [comment]
hi @borg286,

this's kvrocks supports commands https://github.com/meitu/kvrocks/blob/master/docs/support-commands.md, and some commands like `hscan`,`scan`,`info` weren't totally compatible with Redis, we just try our best to compatible with Redis. and some structures like GEO, HYPERLOGLOG would come soon

**Comment by borg286** [comment]
Your docs say it supports hscan, and I did a one-off test to see it worked with 1 element. Perhaps this test may reveal a corner case your code fails at.

**Comment by git-hulk** [comment]
You're right, kvrocks hscan return `not found error` when the hash key was not found which not consistence with Redis. we should fix it, very very thanks for your feedback.
