### ISSUE TITLE
Support column families in KVRocks

### ISSUE THREAD

**Issue by aniruddhadas** [KvrocksLabs/kvrocks#95]
Hi,

I couldn't find anyway of setting up new column families in KVRocks. Is there a way to setup a new namespace KVRocks and execute (redis-cli --pipe) commands against the new column family?

Thanks,
Aniruddha

**Comment by git-hulk** [comment]
hi @aniruddhadas ,  you can use `namespace` command to create/delete/set/list namespaces: https://github.com/bitleak/kvrocks#namspace , but the new namespace wouldn't create new column family actually.

**Comment by aniruddhadas** [comment]
i see thanks @git-hulk.. does using namespace guarantee compartmentalization? or does the data in 2 different namespaces share the same memtables and ssts?

**Comment by git-hulk** [comment]
yeah, we use namespace as  the key prefix instead of different column families
